pipeline:
  build:
    image: maven:3-jdk-8
    commands:
     - mvn clean test verify
  scp:
    image: appleboy/drone-scp
    host: 18.219.176.239
    username: root
    password: redhat
    port: 22
    target: /home/deploy/web
    source: cucumberbasic
  
